# !s390x !ppc64le !arm64
# enable sev-snp support
CONFIG_AMD_MEM_ENCRYPT=y
CONFIG_SEV_GUEST=y
CONFIG_VIRT_DRIVERS=y

# Prepare kernel for direct boot using OVMF
CONFIG_EFI=y
CONFIG_EFI_STUB=y

# IMA stuff
CONFIG_INTEGRITY=y
CONFIG_IMA=y
CONFIG_IMA_APPRAISE=y
CONFIG_IMA_APPRAISE_BOOTPARAM=y
CONFIG_IMA_MEASURE_PCR_IDX=10
CONFIG_IMA_DEFAULT_TEMPLATE="ima-ng"
CONFIG_IMA_NG_TEMPLATE=y
CONFIG_IMA_LSM_RULES=y
CONFIG_IMA_DEFAULT_HASH="sha256"
CONFIG_IMA_DEFAULT_HASH_SHA256=y
CONFIG_IMA_READ_POLICY=y
CONFIG_IMA_WRITE_POLICY=y